# Generated by Django 5.2 on 2025-10-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_distance_away',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
