# Generated by Django 5.2 on 2025-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('van', 'Van'), ('motorbike', 'Motorbike'), ('lorry', 'Lorry')], max_length=20),
        ),
    ]
